name: GoldSiege
main: com.pixelyeti.goldsiege.Main
author: PixelYeti
version: 1.0
description: >
             Gold Siege Plugin

commands:
  SetSpawn:
    description: Set the spawn
  Spawn:
      description: Teleport to the spawn
  TPWorld:
      description: Teleport to a different world
  StartGame:
        description: Start the game of the current player
  EndGame:
        description: End the game of the current player
  AddMapSpawn:
          description: Add a map spawn to the specified map
  ListSpawns:
          description: Add a map spawn to the specified map